export const SITE = {
  name: "Xethra",
  tagline: "The cheapest direct Seedance API",
  title: "Xethra — Direct Seedance API at the Lowest Price",
  description:
    "Generate cinematic AI video with ByteDance Seedance models through a direct API — no reseller markup. Text-to-video, image-to-video, and reference video. From $0.60 per 5s clip. Request API access today.",
  url: "https://www.xethra.com",
  keywords: [
    "Seedance API",
    "Seedance 2.0 API",
    "ByteDance video API",
    "cheapest AI video API",
    "image to video API",
    "text to video API",
    "Seedance pricing",
    "ModelArk API",
    "AI video generation",
    "Xethra",
  ],
} as const;

export const MODES = [
  {
    id: "text",
    title: "Text to Video",
    headline: "Describe it. Watch it move.",
    description:
      "Write a prompt and Seedance builds the scene — camera motion, lighting, subject movement, and atmosphere. Ideal for product shots, B-roll, ads, and social clips without shooting a frame.",
    details: [
      "Full creative control via natural language",
      "5s or 10s duration · 720p or 1080p",
      "Aspect ratios: 9:16, 16:9, 1:1, 4:3, 3:4",
      "Optional audio generation on supported models",
    ],
  },
  {
    id: "image",
    title: "Image to Video",
    headline: "Bring stills to life.",
    description:
      "Upload a photo or paste a URL. Seedance animates it with realistic motion while preserving identity, composition, and style. Perfect for avatar videos, product photos, and portrait content.",
    details: [
      "First frame, last frame, or reference image roles",
      "Preserves faces and brand visuals",
      "Subtle motion to full cinematic movement",
      "Works with JPEG, PNG, WebP, GIF",
    ],
  },
  {
    id: "reference",
    title: "Reference Video",
    headline: "Motion that matches your vision.",
    description:
      "Provide a reference image and describe the motion you want. Seedance uses multimodal understanding to generate video that follows your character, product, or scene reference with high fidelity.",
    details: [
      "Character-consistent avatar campaigns",
      "Lower token cost with video input on 2.0",
      "Combine reference + prompt for precise control",
      "Face-optimized models for real-person content",
    ],
  },
] as const;

export const MARKETING_MODELS = [
  {
    name: "Seedance 1.0 Pro Fast",
    tier: "Free tier",
    price: "2M free tokens",
    perClip: "~$0.05",
    resolution: "Up to 1080p",
    speed: "Fastest",
    highlight: "Best for testing & prototyping",
    available: true,
  },
  {
    name: "Seedance 1.5 Pro",
    tier: "Free tier",
    price: "2M free tokens",
    perClip: "~$0.06",
    resolution: "Up to 1080p",
    speed: "Standard",
    highlight: "Cinematic quality + optional audio sync",
    available: true,
  },
  {
    name: "Seedance 2.0 Fast",
    tier: "Production",
    price: "$5.6 / 1M tokens",
    perClip: "~$0.60",
    resolution: "720p max",
    speed: "2× faster",
    highlight: "High-volume production at speed",
    available: true,
  },
  {
    name: "Seedance 2.0",
    tier: "Production",
    price: "$7.0 / 1M tokens",
    perClip: "~$0.76",
    resolution: "720p – 1080p",
    speed: "Standard",
    highlight: "Flagship quality for final deliverables",
    available: true,
  },
  {
    name: "Seedance 2.0 Face",
    tier: "Production",
    price: "$7.0 / 1M tokens",
    perClip: "~$0.76",
    resolution: "720p – 1080p",
    speed: "Standard",
    highlight: "Real-person reference images",
    available: true,
  },
  {
    name: "Seedance 2.5",
    tier: "Coming soon",
    price: "TBA",
    perClip: "—",
    resolution: "1080p+",
    speed: "Next-gen",
    highlight: "Next generation — join the waitlist",
    available: false,
  },
] as const;

export const COMPARISON = [
  {
    platform: "Xethra (BytePlus direct)",
    perClip: "~$0.76",
    perSec: "~$0.15",
    markup: "Wholesale",
    api: true,
    highlight: true,
    trust: "Direct",
  },
  {
    platform: "Replicate",
    perClip: "~$0.90",
    perSec: "$0.18",
    markup: "+19%",
    api: true,
    highlight: false,
    trust: "High",
  },
  {
    platform: "Segmind",
    perClip: "~$0.91",
    perSec: "$0.18",
    markup: "+20%",
    api: true,
    highlight: false,
    trust: "API",
  },
  {
    platform: "WaveSpeed",
    perClip: "~$1.00",
    perSec: "$0.20",
    markup: "+32%",
    api: true,
    highlight: false,
    trust: "Verified",
  },
  {
    platform: "Kie.ai",
    perClip: "~$1.03",
    perSec: "$0.205",
    markup: "+36%",
    api: true,
    highlight: false,
    trust: "API",
  },
  {
    platform: "fal.ai",
    perClip: "~$1.21",
    perSec: "$0.242",
    markup: "+59%",
    api: true,
    highlight: false,
    trust: "High",
  },
  {
    platform: "fal.ai Standard",
    perClip: "~$1.52",
    perSec: "$0.303",
    markup: "+100%",
    api: true,
    highlight: false,
    trust: "High",
  },
  {
    platform: "Higgsfield",
    perClip: "~$0.73–1.65",
    perSec: "Credits",
    markup: "Sub + credits",
    api: false,
    highlight: false,
    trust: "Studio",
  },
  {
    platform: "Dreamina",
    perClip: "~$1.62",
    perSec: "Credits",
    markup: "Sub + credits",
    api: false,
    highlight: false,
    trust: "Web UI",
  },
] as const;
